service: tangential
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    LOCAL_HTTP_PROXY: http://localhost:8080
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    ATLASSIAN_CLIENT_ID: lKCXKlNw2myH1xNmrapHhpq5KGkbq91j
    ATLASSIAN_CLIENT_SECRET: ATOA-AdVQkT9_X9SJG_Vx_nHyf3u3YjNWI2ho_Tynam2ar3VwEH7xg-ztbH8SY91oUT_511E0D4B

